[pytest]
#Allure
allure_reporting = True

#Параметры тестов
addopts =
    -v
    -s
    --maxfail=20
    --disable-warnings
    --capture=no
    --timeout=180
    --cache-clear
    --tb=short
    --alluredir=allure-results
    --clean-alluredir

markers =
    smoke: Smoke test
    regression: Regression test
    critical: Critical test
    slow: Slow test
    ui: UI test
    api: API test

testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

#Logger
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)s | %(message)s
